# Generated by Django 5.2 on 2026-01-21 04:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompraPadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('unidad', 'Unidad'), ('paquete', 'Paquete'), ('caja', 'Caja')], default='unidad', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('costo_unitario', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_venta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('proveedor', models.CharField(max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('compra_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='inventory.comprapadre')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='inventory.producto')),
            ],
            options={
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('fecha', models.DateField()),
                ('canal_venta', models.CharField(choices=[('local', 'Local'), ('whatsapp', 'WhatsApp'), ('telefono', 'Teléfono'), ('delivery', 'Delivery'), ('otro', 'Otro')], default='local', max_length=20)),
                ('cliente', models.CharField(max_length=200)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('credito', 'Crédito')], default='efectivo', max_length=20)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pagado', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='inventory.producto')),
            ],
            options={
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
