# Generated by Django 5.2 on 2026-01-22 17:08

from django.db import migrations


def reset_numbers_to_null(apps, schema_editor):
    """Reset all numero fields to NULL so they are calculated dynamically"""
    Venta = apps.get_model('inventory', 'Venta')
    Compra = apps.get_model('inventory', 'Compra')
    CompraPadre = apps.get_model('inventory', 'CompraPadre')
    
    # Reset all numero fields to NULL
    Venta.objects.all().update(numero=None)
    Compra.objects.all().update(numero=None)
    CompraPadre.objects.all().update(numero=None)


def no_op(apps, schema_editor):
    """Reverse operation does nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_producto_id_producto_alter_producto_unidad_medida'),
    ]

    operations = [
        migrations.RunPython(reset_numbers_to_null, no_op),
    ]
